### ISSUE TITLE
Divide by zero

### ISSUE THREAD

**Issue by JusbeR** [viesti/clj-lttb#1]
Crashes to this line if you try to get stuff downsampled to 2 https://github.com/viesti/clj-lttb/blob/main/src/lttb/core.cljc#L8

Not that is probably make any sense to do it, but still. :)

**Comment by viesti** [comment]
Ah, good find, could probably guard against this :)

**Comment by viesti** [comment]
Make a quick fix in 8ae80e8d215dae3a94df3da25e2007aa636d897e
